// <auto-generated />
using System;
using APIBarDG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIBarDG.Migrations
{
    [DbContext(typeof(ComandaContext))]
    [Migration("20200729035713_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("APIBarDG.Model.Comanda.Comanda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("PromocaoAguaPedidos")
                        .HasColumnType("REAL");

                    b.Property<double>("PromocaoAguaRestantes")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("APIBarDG.Model.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComandaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("ComandaID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("APIBarDG.Model.Item", b =>
                {
                    b.HasOne("APIBarDG.Model.Comanda.Comanda", null)
                        .WithMany("Itens")
                        .HasForeignKey("ComandaID");
                });
#pragma warning restore 612, 618
        }
    }
}
